# Generated by Django 4.1.7 on 2023-12-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('about_me', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('achievement', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('school_10th', models.CharField(default='', max_length=50, null=True)),
                ('school_12th', models.CharField(default='', max_length=50, null=True)),
                ('score_10th', models.CharField(default='', max_length=50, null=True)),
                ('score_12th', models.CharField(default='', max_length=50, null=True)),
                ('UG_college', models.CharField(default='', max_length=50, null=True)),
                ('UG_course', models.CharField(default='', max_length=50, null=True)),
                ('score_UG', models.CharField(default='', max_length=50, null=True)),
                ('PG_coollege', models.CharField(default='', max_length=50, null=True)),
                ('PG_course', models.CharField(default='', max_length=50, null=True)),
                ('score_PG', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('job_role', models.CharField(default='', max_length=50)),
                ('start_date', models.CharField(default='', max_length=50)),
                ('end_date', models.CharField(default='', max_length=50)),
                ('decription', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('language', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('email', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('lanme', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('project_name', models.CharField(default='', max_length=50)),
                ('project_description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('skill_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocailLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('link_name', models.CharField(default='', max_length=50)),
                ('link', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=30, null=True)),
                ('template_name', models.CharField(default='', max_length=50)),
                ('template_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
