# Generated by Django 4.1.7 on 2023-12-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeKraft', '0003_alter_aboutme_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='about_me',
            field=models.CharField(default='', max_length=300),
        ),
    ]
